### ISSUE TITLE
Potencia

### ISSUE THREAD

**Issue by rcampa1** [lore123/Calculadora#11]
Realizar la potencia números

**Comment by ansac81** [comment]
public class Potencia 
    public void potencia()

**Comment by jorgebarajas** [comment]
por favor pasame correctamente la instanciacion a tu clase si es que asi aplica o el llamamiento de tu clase con el metodo que se ejecuta

**Comment by ansac81** [comment]
Potencia poten=new Potencia();
poten.potencia();
